### ISSUE TITLE
Cannot build for iOS: unknown receiver 'AdjustSdk'

### ISSUE THREAD

**Issue by alexregier** [adjust/flutter_sdk#26]
When trying to build for iOS we get this error from Xcode:

> /.../ios/Runner/GeneratedPluginRegistrant.m:173:4: error: unknown receiver 'AdjustSdk'; did you mean 'ADJAdjustSdk'?
  [AdjustSdk registerWithRegistrar:[registry registrarForPlugin:@"AdjustSdk"]];
   ^~~~~~~~~
   ADJAdjustSdk
In module 'adjust_sdk' imported from /.../ios/Runner/GeneratedPluginRegistrant.m:14:
/.../build/ios/Debug-iphonesimulator/adjust_sdk/adjust_sdk.framework/Headers/AdjustSdk.h:11:12: note: 'ADJAdjustSdk' declared here
@interface ADJAdjustSdk : NSObject<FlutterPlugin>

How can we solve this issue?

Versions:
Adjust 4.23.0
Flutter 1.20.2

**Comment by ugi** [comment]
Hey @alexregier 

Thanks for reporting, will be checked. Will keep you posted.

**Comment by alexregier** [comment]
With Adjust version 4.22.1 it seems to work properly 🤔

**Comment by creativecreatorormaybenot** [comment]
@ugi 

This means that the following is true (`pubspec.yaml`):

```yaml
dependencies:
  adjust_sdk: ^4.22.1 # FAILS (when pub upgrade was run)
  adjust_sdk: ^4.23.0 # FAILS
  adjust_sdk: 4.22.1 # iOS build succeeds (locked version to 4.22.1)
```
